version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: oimo-billing-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - oimo-billing-network
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: oimo-billing-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: oimo_billing
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - oimo-billing-network

  redis:
    image: redis:alpine
    container_name: oimo-billing-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - oimo-billing-network

  nginx:
    image: nginx:alpine
    container_name: oimo-billing-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - oimo-billing-network
    depends_on:
      - app

networks:
  oimo-billing-network:
    driver: bridge

volumes:
  dbdata:
    driver: local 